sonar.organization=<YOUR_SONAR_ORG>
sonar.projectKey=<YOUR_SONAR_ORG>_-RE-Source-backend
sonar.projectVersion=1.0.0
sonar.language=js
sonar.sources=src
sonar.tests=src/tests
sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.exclusions=node_modules/**,src/tests/**,dist/**
sonar.qualityGate.wait=false
