name: 02-4 - Staging - Deploy App

on:
  workflow_call:
    secrets:
      AZURE_CLIENT_ID:
        required: true
      AZURE_TENANT_ID:
        required: true
      AZURE_SUBSCRIPTION_ID:
        required: true
      AZURE_VM_LOGIN:
        required: true
      AZURE_VM_PASSWORD:
        required: true
      PAT_TOKEN:
        required: true
      FRONT_IMAGE_CANARY:
        required: true
      MONGO_ROOT_PASSWORD:
        required: true
      JWT_SECRET:
        required: true

jobs:
  Deploy:
    runs-on: ubuntu-22.04

    env:
      ResourceGroupName: "RessourcesRelationnelles-Staging"

    steps:
      - name: Azure Login
        uses: azure/login@a457da9ea143d694b1b9c7c869ebb04ebe844ef5 # v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Get Public IP
        uses: azure/CLI@9f7ce6f37c31b777ec6c6b6d1dfe7db79f497956 # v2
        with:
          inlineScript: |
            echo "AZURE_VM_IP=$(az vm show -d -g ${{env.ResourceGroupName}} -n vm-staging --query publicIps -o tsv)" >> $GITHUB_ENV

      - name: Checkout
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4

      - name: Copy docker-compose to VM
        uses: appleboy/scp-action@917f8b81dfc1ccd331fef9e2d61bdc6c8be94634 # v0.1.7
        with:
          host: ${{env.AZURE_VM_IP}}
          port: 22
          username: ${{secrets.AZURE_VM_LOGIN}}
          password: ${{secrets.AZURE_VM_PASSWORD}}
          source: "./docker-compose.yml"
          target: "."

      - name: Downcase Image Name
        run: echo "IMAGE_NAME_LOWER=$(echo ${GITHUB_REPOSITORY,,} | sed 's|/-|/|g')" >> $GITHUB_ENV

      - name: Start Application
        uses: appleboy/ssh-action@029f5b4aeeeb58fdfe1410a5d17f967dacf36262 # v1.0.3
        with:
          host: ${{env.AZURE_VM_IP}}
          port: 22
          username: ${{secrets.AZURE_VM_LOGIN}}
          password: ${{secrets.AZURE_VM_PASSWORD}}
          script: |
            echo ${{secrets.PAT_TOKEN}} | docker login ghcr.io -u ${{github.actor}} --password-stdin

            echo MONO_PROJECT_BACK=ghcr.io/${{env.IMAGE_NAME_LOWER}}:canary > .env
            echo MONO_PROJECT_FRONT=${{secrets.FRONT_IMAGE_CANARY}} >> .env
            echo MONGO_ROOT_PASSWORD=${{secrets.MONGO_ROOT_PASSWORD}} >> .env
            echo MONGO_DATABASE=ressources_relationnelles >> .env
            echo JWT_SECRET=${{secrets.JWT_SECRET}} >> .env

            docker pull ghcr.io/${{env.IMAGE_NAME_LOWER}}:canary
            docker pull ${{secrets.FRONT_IMAGE_CANARY}}

            docker compose down || true
            docker compose up -d
