name: 02 - Staging

on:
  push:
    branches:
      - develop
      - release/*

jobs:
  # -- Merge sur develop : build + scan image canary --
  Build_Push_Docker:
    if: github.ref_name == 'develop'
    uses: ./.github/workflows/02-1_DockerBuild.yml
    secrets:
      PAT_TOKEN: ${{ secrets.PAT_TOKEN }}
    with:
      docker-mode: canary

  Trivy_Scan:
    needs: [Build_Push_Docker]
    if: github.ref_name == 'develop'
    uses: ./.github/workflows/02-2_Trivy.yml
    secrets:
      PAT_TOKEN: ${{ secrets.PAT_TOKEN }}

  # -- Push sur release/* : déploiement staging --
  Bicep_Deploy:
    if: startsWith(github.ref, 'refs/heads/release/')
    uses: ./.github/workflows/02-3_BicepDeploy.yml
    secrets:
      AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
      AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      AZURE_VM_LOGIN: ${{ secrets.AZURE_VM_LOGIN }}
      AZURE_VM_PASSWORD: ${{ secrets.AZURE_VM_PASSWORD }}
      PORT: ${{ secrets.PORT }}
    permissions:
      id-token: write

  Deploy_App:
    needs: [Bicep_Deploy]
    if: startsWith(github.ref, 'refs/heads/release/')
    uses: ./.github/workflows/02-4_DeployApp.yml
    secrets:
      AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
      AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      AZURE_VM_LOGIN: ${{ secrets.AZURE_VM_LOGIN }}
      AZURE_VM_PASSWORD: ${{ secrets.AZURE_VM_PASSWORD }}
      PORT: ${{ secrets.PORT }}
      PAT_TOKEN: ${{ secrets.PAT_TOKEN }}
      FRONT_IMAGE_CANARY: ${{ secrets.FRONT_IMAGE_CANARY }}
      MONGO_ROOT_PASSWORD: ${{ secrets.MONGO_ROOT_PASSWORD }}
      JWT_SECRET: ${{ secrets.JWT_SECRET }}
    permissions:
      id-token: write

  Zap_Scan:
    needs: [Bicep_Deploy, Deploy_App]
    if: startsWith(github.ref, 'refs/heads/release/')
    uses: ./.github/workflows/02-5_ZapScan.yml
    permissions:
      issues: write
    with:
      vm_ip: ${{ needs.Bicep_Deploy.outputs.vm_ip }}
